name: Coverage

on: [ push ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: xdebug
          tools: phpunit
          coverage: xdebug

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: View Version
        run: composer -V

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPUnit Coverage
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.1
          php_extensions: xdebug
          configuration: tests/phpunit.xml
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
